name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose version

      - name: Build services
        run: docker compose -f infra/docker-compose.yaml build



  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Set the path to your project on the Droplet
            PROJECT_PATH="/home/${{ secrets.SSH_USER }}/your-project"

            # Check if the directory exists
            if [ ! -d "$PROJECT_PATH" ]; then
              echo "Directory does not exist. Cloning repository..."
              git clone https://github.com/${{ github.repository }}.git "$PROJECT_PATH"
            fi

            # Navigate to the project directory
            cd "$PROJECT_PATH"

            # Pull the latest changes
            git pull origin main

            # Stop and remove old containers
            docker compose -f infra/docker-compose.yaml down

            # Build and start new containers
            docker compose -f infra/docker-compose.yaml up -d --build --remove-orphans